run.sh, ukrdc_fastapi/config.py, ukrdc_fastapi/main.py, ukrdc_fastapi/routers/api/dashboard.py
=> Allow multiple dashboard messages and warnings

poetry.lock, pyproject.toml, tests/conftest.py, tests/test_dashboard.py, tests/test_workitems.py, ukrdc_fastapi/config.py, ukrdc_fastapi/dependencies/auth.py, ukrdc_fastapi/dependencies/okta/__init__.py, ukrdc_fastapi/main.py, ukrdc_fastapi/routers/api/dashboard.py, ukrdc_fastapi/routers/api/empi/linkrecords.py, ukrdc_fastapi/routers/api/empi/masterrecords.py, ukrdc_fastapi/routers/api/empi/persons.py, ukrdc_fastapi/routers/api/empi/search.py, ukrdc_fastapi/routers/api/empi/workitems.py, ukrdc_fastapi/routers/api/errors.py, ukrdc_fastapi/routers/api/laborders.py, ukrdc_fastapi/routers/api/mirth.py, ukrdc_fastapi/routers/api/patientrecords.py, ukrdc_fastapi/routers/api/resultitems.py, ukrdc_fastapi/routers/api/user.py, ukrdc_fastapi/schemas/patientrecord.py
Migrated authentication and authorisation to Okta
=> Okta-based authentication

README.md, ukrdc_fastapi/config.py, ukrdc_fastapi/main.py
Added DB and Redis connection checks to startup, and added README notes on how to set these connections up locally.
=> Check all connections on startup

poetry.lock, pyproject.toml, tests/test_routers/test_masterrecords.py, ukrdc_fastapi/query/errors.py, ukrdc_fastapi/query/facilities.py, ukrdc_fastapi/routers/api/empi/masterrecords/record_id.py, ukrdc_fastapi/routers/api/empi/workitems/workitem_id.py, ukrdc_fastapi/schemas/empi.py
Mostly commits related to scheduled tasks and caching
=> 2021-06-29

ukrdc_fastapi/query/resultitems.py
Closes https://jira.ukrdc.org/browse/UI-55
=> Fixed resultitem sorting

ukrdc_fastapi/routers/api/v1/masterrecords/record_id.py
Workaround for https://jira.ukrdc.org/browse/UI-56. 
For some reason, if you log in as a non-admin user, `related_ukrdc_records.count()` returns the wrong value sometimes, despite the query returning the right data.
This has ben verified by logging `related_ukrdc_records.all()`, and counting with `len(related_ukrdc_records.all()`.
I truly, deeply do not understand why this would happen, so I've had to implement this slightly slower workaround. 
Assuming the patient doesn't somehow have hundreds of, UKRDC records, the speed decrease should be negligable.
=> Workaround for UI-56

poetry.lock, pyproject.toml
Changes default first page to 1 (from 0) so requires https://github.com/renalreg/ukrdc-nuxt/pull/27
=> Upgrade fastapi-pagination

tests/conftest.py, tests/test_query/test_codes.py, ukrdc_fastapi/query/codes.py, ukrdc_fastapi/routers/api/v1/codes.py, ukrdc_fastapi/schemas/code.py
Rearranges the codes API slightly, and adds maps to code details.
=> Codes API improvements

tests/test_query/test_mirth/test_merge.py, tests/test_query/test_mirth/test_unlink.py, tests/test_routers/test_empi.py, tests/test_routers/test_workitems.py, ukrdc_fastapi/exceptions.py, ukrdc_fastapi/query/mirth/unlink.py, ukrdc_fastapi/query/persons.py, ukrdc_fastapi/routers/api/v1/empi.py, ukrdc_fastapi/schemas/base.py
Resolves https://jira.ukrdc.org/browse/UI-70
=> Improve global merge and unlink API routes

ukrdc_fastapi/dependencies/auth.py, ukrdc_fastapi/routers/api/v1/empi.py, ukrdc_fastapi/routers/api/v1/persons.py, ukrdc_fastapi/routers/api/v1/search.py, ukrdc_fastapi/routers/api/v1/workitems/workitem_id.py
Required for https://github.com/renalreg/ukrdc-nuxt/pull/54
=> Re-introduced separate permission for editing the EMPI

tests/test_routers/test_empi.py, ukrdc_fastapi/query/mirth/merge.py, ukrdc_fastapi/routers/api/v1/empi.py, ukrdc_fastapi/utils/mirth.py
Requires https://github.com/renalreg/ukrdc-nuxt/pull/55
=> Fixed spelling of supersede above Mirth message level

ukrdc_fastapi/routers/api/v1/search.py
Required for https://github.com/renalreg/ukrdc-nuxt/pull/60
=> Add param to search only UKRDC records

ukrdc_fastapi/exceptions.py, ukrdc_fastapi/main.py, ukrdc_fastapi/query/mirth/merge.py, ukrdc_fastapi/query/mirth/unlink.py, ukrdc_fastapi/query/mirth/workitems.py, ukrdc_fastapi/routers/api/v1/patientrecords/pid/export.py
This should allow Sentry to handle exceptions raised upstream (Mirth etc)
=> Raise generic exceptions for Mirth errors

ukrdc_fastapi/query/workitems.py, ukrdc_fastapi/schemas/empi.py
Identifies work items raised by the same event and includes them in the detailed work item resource
=> Add work item collection attribute

poetry.lock, pyproject.toml, tests/conftest.py, tests/test_query/test_errors.py, tests/test_query/test_masterrecords.py, tests/test_query/test_workitems.py, tests/test_routers/test_masterrecords.py, tests/test_routers/test_persons.py, tests/test_routers/test_workitems.py, ukrdc_fastapi/query/workitems.py, ukrdc_fastapi/routers/api/v1/workitems/workitem_id.py, ukrdc_fastapi/schemas/empi.py
* Traverse link tree to identify related work items
* Separate workitem collection into separate route
* Updated UKRDC-SQLA to add creation date attribute to workitems
=> Additional WorkItem fixes

poetry.lock, pyproject.toml, ukrdc_fastapi/schemas/patient.py, ukrdc_fastapi/schemas/patientrecord.py
Partially resolves https://jira.ukrdc.org/browse/UI-103
=> Add GP info to FamilyDoctor and FamilyDoctor to all Patient resources

tests/conftest.py, tests/test_query/test_delete.py, tests/test_query/test_masterrecords.py, tests/test_query/test_mirth/test_unlink.py, tests/test_query/test_patientrecords.py, tests/test_query/test_workitems.py, tests/test_routers/test_empi.py, tests/test_routers/test_masterrecords.py, tests/test_routers/test_messages.py, tests/test_routers/test_patientrecord/test_delete.py, tests/test_routers/test_patientrecords.py, tests/test_routers/test_persons.py, tests/test_routers/test_search.py, tests/test_routers/test_workitems.py, tests/utils.py, ukrdc_fastapi/routers/api/v1/search.py, ukrdc_fastapi/utils/__init__.py, ukrdc_fastapi/utils/search/masterrecords.py
Replaced EMPI-based search with UKRDC3-based search.
Search still returns master records, but search logic uses UKRDC3 allowing us to search by more parameters.
Now also includes a facility search.
=> Base search on UKRDC3 database

tests/conftest.py, tests/test_query/test_codes.py, tests/test_query/test_facilities.py, tests/test_routers/test_codes.py, tests/test_routers/test_facilities.py, tests/utils.py, ukrdc_fastapi/query/facilities/__init__.py, ukrdc_fastapi/query/facilities/errors.py, ukrdc_fastapi/query/facilities/stats/demographics.py, ukrdc_fastapi/query/messages.py, ukrdc_fastapi/query/stats.py, ukrdc_fastapi/routers/api/v1/facilities.py, ukrdc_fastapi/schemas/facility.py
Relates to https://github.com/renalreg/ukrdc-nuxt/pull/150
=> Added basic facility demographic distribution stats

ukrdc_fastapi/dependencies/database.py
=> Remove same thread check on sqlite connections

README.md
Adds links to newly published API and client library documentation
=> Added documentation links to README

.github/workflows/main.yml, tests/test_query/test_facilities.py, tests/test_routers/test_admin.py, ukrdc_fastapi/config.py, ukrdc_fastapi/dependencies/cache.py, ukrdc_fastapi/query/facilities/__init__.py, ukrdc_fastapi/routers/api/admin/__init__.py, ukrdc_fastapi/routers/api/facilities/__init__.py, ukrdc_fastapi/schemas/facility.py
Closes https://github.com/renalreg/ukrdc-fastapi/issues/432
=> Cache admin counts and admin facilities list

poetry.lock, pyproject.toml, tox.ini, ukrdc_fastapi/routers/api/search.py, ukrdc_fastapi/schemas/patientrecord.py
=> Dependency-updates-2023-03

poetry.lock, pyproject.toml, tests/test_routers/test_facilities.py, tox.ini, ukrdc_fastapi/query/facilities/stats.py, ukrdc_fastapi/routers/api/facilities/stats.py, ukrdc_fastapi/tasks/repeated.py, ukrdc_fastapi/utils/cache.py
=> Upgrade stats to v1 and replace dialysis stats with new KRT stats

pyproject.toml, tests/conftest.py, tests/test_query/test_facilities.py, tests/test_query/test_messages.py, tests/test_routers/test_masterrecords.py, ukrdc_fastapi/query/facilities/errors.py, ukrdc_fastapi/query/messages.py, ukrdc_fastapi/routers/api/facilities/__init__.py, ukrdc_fastapi/routers/api/masterrecords/record_id.py, ukrdc_fastapi/routers/api/messages.py, ukrdc_fastapi/routers/api/mirth.py, ukrdc_fastapi/utils/mirth/__init__.py
=> UI-212 - Filter messages by channel ID

ukrdc_fastapi/query/facilities/reports.py
FYI @George-D-S this should get CC001 to work again. I was doing it in a stupid way.
=> Rewrite and optimise get_facility_report_cc001

ukrdc_fastapi/schemas/patientrecord.py
Resolves https://renalregistry.atlassian.net/browse/UI-205
=> Add pvdata to PatientRecordSummarySchema

poetry.lock, pyproject.toml, ukrdc_fastapi/query/facilities/reports.py, ukrdc_fastapi/routers/api/facilities/reports.py
Resolves https://renalregistry.atlassian.net/browse/UI-214
=> Exclude patients with known DoD > 5 years ago from CC001

tests/test_query/test_users.py, tests/test_routers/test_system.py, ukrdc_fastapi/schemas/user.py
Replaces the now-unused showUkrdc user preference with a placeholder
=> Remove unused showUkrdc preference

tests/test_routers/test_workitems.py, ukrdc_fastapi/routers/api/workitems/workitem_id.py, ukrdc_fastapi/schemas/empi.py
- Work around JTRACE always including DoB in WorkItem attributes
- Update work items related messages route to target messages from the time the work item was raised
=> Improve work item attributes and related messages

ukrdc_fastapi/routers/api/patientrecords/__init__.py
Changes the new transplant route to match other treatments in not using pagination
=> fix: don't paginate transplant items
